Elevate Linux Permissions,Introduce Command Line Switches
sqrldev/SQRLDotNetClient pull request #200
Opened 2020-05-16 00:05 UTC by josegomez

This Pull Request Addresses issue #196 
It also introduces command line switch support in the Installer for actions
Install, Uninstall and (eventual) Update #197 (Separate PR)

2020-05-16 03:24 UTC, josegomez commented
@alexhauser I threw the review request out there while I'm investigating in case you have any feedback or ideas in the mean time.

2020-05-16 08:46 UTC, alexhauser commented
@josegomez, first of all, this is looking great! 

I would love it if we could get the path mapping to work with this, as the elevation process looks as user-friendly as it can be. 

Also, your approach on the command line parsing is beautiful, I love it!

As for the path mapping issue: 
This is really infuriating. `sudo` does handle this very well. Even in a `sudo` session, `$HOME` will map to the original user's home path, which is what you want almost all of the time. The more disappointing it is, that it seems PolicyKit doesn't support this beahiviour.

If we try to map the paths locally, you could try using the `logname` command instead of having to pass around command line arguments, since that should give you the name of the currently logged in user, irrespective of any "elevation" level. I haven't tried it with PolicyKit, but it should hopefully work there as well.

I will give this some more thought as well, and poke around a little.

Proper code review will follow once the PR is complete.

2020-05-16 13:40 UTC, josegomez commented
Yeah polkit does more of a run as than a sudo invoke unfortunately 
I’ll keep working the problem

2020-05-16 13:48 UTC, josegomez commented
I just had an idea not sure how well it will work but if we run export HOME = path/to/current/user/home 
That should remap HOME to the right place for the session 
I wonder if then the special folder stuff will work correctly...
I gotta assume they use environment variables to determine

2020-05-16 13:58 UTC, alexhauser commented
@josegomez, have you tried `logname` as suggested above?

```C#
string user = _shell.Term("logname", Output.Hidden).stdout.Trim();
```

2020-05-16 14:40 UTC, josegomez commented
@alexhauser I just checked and logname does show the current logged on user correctly.!

2020-05-16 14:47 UTC, alexhauser commented
Cool, then we do at least have another option, @josegomez.

You should be able to get the full home path of the user like this:

```C#
string user = _shell.Term("logname", Output.Hidden).stdout.Trim();
string home = _shell.Term($"getent passwd {user} | cut -d: -f6", Output.Hidden).stdout.Trim();
```

This is from here: https://unix.stackexchange.com/questions/247576/how-to-get-home-given-user

If we add that to `PathConf` if we detect that `Util.IsAdmin() == true`, we should be good, no?

2020-05-16 14:49 UTC, josegomez commented
yeah that should work .net core uses the following to get the special folders
![image](https://user-images.githubusercontent.com/420837/82122649-de46ea00-9762-11ea-981e-3b324f61c382.png)

And this to get the Home Directory
![image](https://user-images.githubusercontent.com/420837/82122658-ed2d9c80-9762-11ea-9173-684b566b8000.png)

2020-05-16 14:54 UTC, alexhauser commented
Ah, they fall back to `/etc/passwd` too if the environment variable does not exist. The `getent` tool also looks into `/etc/passwd`, since that's the only place where the home directory is guaranteed to exist.

2020-05-16 21:19 UTC, josegomez commented
Well what a CLUSTER ! I think I got it... If you don't mind @alexhauser when looking through the code be a bit more thorough than normal there were a lot of things I had to change and do this will require some serious testing before release.

Current Experience should be as follows 
Initial Install:
Because upon Initial Inistall we won't be able to automatically elevate (no polikit rules in place) the software will prompt you to run as sudo
![InitialInstall](https://user-images.githubusercontent.com/420837/82130319-5e3b7700-9798-11ea-9274-a3e8043406c3.gif)


Updates and Subsequent Installs:
Updates and subsequent Installs will (should) automatically Elevate and execute.
![Updates](https://user-images.githubusercontent.com/420837/82130324-70b5b080-9798-11ea-8344-f44fab203afb.gif)

The logic for this got pretty complex, the initial install creates the polkit rules so that the file can be elevated. These polkit rules require a specific Path so I make this path be 
"/tmp/SQRLPlatformAwareInstaller_linux"

The reason for this is as follows

When the installer runs (as non root) it will automatically copy itself into /tmp/ so that when the elevation occurs the latest (current) copy of the Installer exists in /tmp/ 

The reason I put it in /tmp/ is because if we ran it directly from /opt/SQRL then when  the unzip operation occurs the installer is in use and causes conflict.

So to summarize
If the installer runs as non root the first time
It asks the user to run as sudo and bails
Then the install process runs as normal and it creates the polkit rules

Next Time
If the Installer runs as non root

- The installer copies itself to /tmp/SQRLPlatformAwareInstaller_linux
- The installer creates a script in temp which invokes polkit and the above copy of the installer
- The installer bails
- The above script invokes polkit elevation and launches /tmp/SQRLPlatformAwareInstaller_linux (as root)
- Because the program is running from /tmp/SQRLPlatformAwareInstaller_linux there is no conflict with over-writing or copying files into /opt/SQRL where it originally lives

2020-05-17 08:19 UTC, alexhauser requested changes
Fantastic job Jose, great to see that you got everything working! 🎉

I guess you'll probably regret asking me to be thorough. But never the less, here you go with my (somewhat pedantic) review.

In general, we could maybe look into encapsulating all the PolicyKit-related nitty-gritty into its own class (or maybe use the `AdminCheck` class), in order to de-clutter the higher-level "logic"-code in the Installer and in App classes. Don't know if it's possible, but could be worth exploring.

2020-05-17 08:19 UTC, alexhauser commented on SQRLCommonUI/Models/PathConf.cs
> +                    string home = _shell.Term($"getent passwd {user} | cut -d: -f6", Output.Hidden).stdout.Trim();
To avoid duplicating code, I would suggest pulling this out into a function á la 
```C#
public static string GetHomePath()
```

2020-05-17 08:19 UTC, alexhauser commented on SQRLCommonUI/Models/PathConf.cs
> +                    string home = _shell.Term($"getent passwd {user} | cut -d: -f6", Output.Hidden).stdout.Trim();
See my comment about pulling this out into its own method.

2020-05-17 08:19 UTC, alexhauser commented on SQRLCommonUI/Models/PathConf.cs
> +            Log.Information($"Config File:{ConfFile}");
Missing space after colon. (You told me to be thorough 😉)

2020-05-17 08:19 UTC, alexhauser commented on SQRLCommonUI/SQRLCommonUI.csproj
> +    </None>
Hmmm... full local paths, that doesn't look right. Or is it?

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/App.xaml.cs
> +                                Log.Information($"Copying Installer From:{Process.GetCurrentProcess().MainModule.FileName} to: /tmp/SQRLPlatformAwareInstaller_linux");
Missing space after colon.

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/Assets/Localization/localization.json
> +      "BtnExit": "Ausfahrt",
LOL, this would be the "highway exit". Correct translation is "Beenden".

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/Assets/Localization/localization.json
> +      "RootAccessRequired": "Für die Installation / Aktualisierung von SQRL ist Root- oder Administratorzugriff erforderlich.\r\n\r\nDie Sitzung konnte nicht automatisch erhöht werden. Schließen Sie
That's almost right! 😁

`Für die Installation / Aktualisierung von SQRL ist Root- oder Administratorzugriff erforderlich.\r\n\r\nDie Berechtigung der aktuellen Sitzung konnte nicht automatisch erhöht werden. Schließen Sie das Installationsprogramm und führen Sie es mit \"sudo\" erneut aus.`

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/Assets/SQRLPlatformAwareInstaller_linux.policy
> +    <description>Run SQRL Platform Installer  Program</description>
Double space

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/Models/CommandLineArgs.cs
> +    /// by default it would be Install, but we also have the option to Unininstall and eventually upgrade the application.
typo in "Uninstall"

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/Models/CommandLineArgs.cs
> +        /// Command line switch -p | -path "path hold's SQRL current install path
Description you used below is better: `"Specifies SQRL's current Install path (directory)"`

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/Models/CommandLineArgs.cs
> +        /// Command line switch -z | zip "path to update zip" holds the path ofthe downloaded update zip
ofthe (missing space).
Also, the description you use below is nicer: `"Specifies the location of the temporary update zip file (used in conjunction with update action)"`

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/Platform/Linux/Installer.cs
> +                }
If we implement `GetHomePath()` in `PathConf` as suggested, we could even make it `public static` and use it here as well. Ideally, this whole upper block could then be replaced with:

```C#
var home = PathConf.GetHomePath();
_shell.Term($"update-desktop-database {home}/.local/share/applications/", Output.Internal);
```

Should this `getent`-hack bite us in the future, it would just be so much cleaner to only have to change it in one central place instead of needing to search every instance of it being used scattered around the project.

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/Platform/Linux/Installer.cs
> +                Log.Information("All us good up to this point, lets setup Linux for UAC (if we can)");
"All **i**s good..." (typo)

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/Platform/Linux/Installer.cs
> +                if (string.IsNullOrEmpty(result.stderr) && !string.IsNullOrEmpty(result.stdout))
This check is also used more than once throughout the code.
Something like `AdminCheck.IsPolicyKitInstalled()` or similar could make everything easier to read and maintain.

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/Platform/Linux/Installer.cs
> +
Same here, this conditional shouldn't be necessary when using `PathConf.GetHomePath()`.

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/Utils.cs
> +            }
Any special reason for adding this? Shouldn't our call to

```c#
_shell.Term($"chmod -R 755 {installPath}", Output.Internal);
```
after the extraction already take care of this?

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/ViewModels/MainWindowViewModel.cs
> +        public MainWindowViewModel(bool rootBail=false)
Some documentation for the new parameter would be nice here.

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/ViewModels/MainWindowViewModel.cs
> +
Excess whitespace.

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/ViewModels/MainWindowViewModel.cs
> +            else if(InstallerCommands.Instance.Action== InstallerAction.Install)
Above, we do a `null` check on `InstallerCommands.Instance`.
Is it not required here as well?

2020-05-17 08:19 UTC, alexhauser commented on SQRLCommonUI/Models/PathConf.cs
> +
Excess whitespace.

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/App.xaml.cs
> +
Excess whitespace.

2020-05-17 08:19 UTC, alexhauser commented on SQRLPlatformAwareInstaller/Views/RootBailView.xaml
> +
Whitespace/formatting.

2020-05-17 12:57 UTC, josegomez commented
Haha no problem this was a big and troublesome change better thorough than not! 
Thanks !

2020-05-17 13:06 UTC, josegomez commented on SQRLCommonUI/Models/PathConf.cs
> +            Log.Information($"Config File:{ConfFile}");
Bahaha 😂 fair enough

2020-05-17 13:17 UTC, josegomez commented on SQRLCommonUI/SQRLCommonUI.csproj
> +    </None>
It did that on its own since these files come from Nuggets I’m not sure how to fix it I’ll poke about

2020-05-17 13:19 UTC, josegomez commented on SQRLPlatformAwareInstaller/Assets/Localization/localization.json
> +      "BtnExit": "Ausfahrt",
lol I’ll blame google for this

2020-05-17 13:20 UTC, josegomez commented on SQRLPlatformAwareInstaller/Utils.cs
> +            }
I missed that yup!

2020-05-17 15:39 UTC, josegomez commented on SQRLCommonUI/Models/PathConf.cs
> +                    string home = _shell.Term($"getent passwd {user} | cut -d: -f6", Output.Hidden).stdout.Trim();
Added 2 Methods to AdminCheck GetUser and GetHome

2020-05-17 15:39 UTC, josegomez commented on SQRLCommonUI/Models/PathConf.cs
> +            Log.Information($"Config File:{ConfFile}");
Fixed

2020-05-17 17:39 UTC, alexhauser approved these changes
Looks good Jose, only one more minor comment.
Merge away!

2020-05-17 17:39 UTC, alexhauser commented on SQRLPlatformAwareInstaller/App.xaml.cs
> +                            Log.Information("pkexec exists!");
Why not  use `SystemAndShellUtils.IsPolKitAvailable()` here?

2020-05-17 18:12 UTC, josegomez commented
@alexhauser made a few more modifications.

2020-05-17 19:08 UTC, alexhauser commented
LGTM! 👍🏻

2020-05-17 19:20 UTC, alexhauser approved these changes

2020-05-17 20:31 UTC, merged